export const uiStrings = {
	appTitle1: "TRIVIA FIT",
	tivra: "TIVRA",
	health: "Health",
	signIn: {
		username: "Username",
		password: "Password",
		forgotPassword: "Forgot Password",
		doNotHaveAccount: "Don't have an account?",
		signUp: "Sign Up",
		rememberMe: "Remember me",
		login: "Login",
		loginButtonText: "Log In",
		privacyStatement: "Privacy Statement",
		forgot: "Forgot Password",
		Email: "Email",
		resetPassword: "Reset Password",
		ButtonText: "Send-OTP",
		Submit: "Submit",
		confirmPassword: "ConfirmPassword",
		setButtonText: "setButtonText",
		required: " required",
	},
	signUp: {
		signUp: "Sign Up",
		signIn: "Sign In",
		step1: "Step 1",
		step2: "Step 2",
		step3: "Step 3",
		step4: "Step 4",
		step5: "Step 5",
		back: "Back",
		stepm1: "1",
		stepm2: "2",
		stepm3: "3",
		stepm4: "4",
		stepm5: "5",
		createYourAccount: "Create your Account",
		createYourProfile: "Create your profile",
		registerYourDevice: "Device Registration",
		paymentDetails: "Payment  Details",
		alreadyHaveAnAccount: "Already have an account",
		registerYourDeviceSubTitle:
			"To register your device, please select your device type below and follow the steps to sign into your account. This will allow us to pull all your information from your device into your TIVRA Fit dashboard.",
		continueText: "Continue",
		verify: "Verify",
		createAccount: "Create Account",
		otpEmailMessage:
			"One time password (OTP) has been sent your registered email ID. Please enter the otp to verify.",
		firstName: "First Name",
		middleName: "Middle Name",
		lastName: "Last Name",
		email: "Email (this will be your username)",
		phoneNumber: "Phone Number (Mobile)",
		verified: "Verified",
		failed: "Failed",
		password: "Password",
		confirmPassword: "Confirm Password",
		otp: "OTP",
		fitBit: "Fitbit",
		garmin: "Garmin",
		myFitnessPal: "MyFitnessPal",
		agreement1: "I certify that I have read and accept TIVRA Health and TIVRA Fit's",
		termsAndConditions: "Terms & conditions",
		privacyPolicy: "Privacy Policy",
		register: "Register",
		proceedToDeviceRegistration: "Proceed to device registration",
		demographicDetailsTitle: "Demographic Profile",
		demographicDetailsTip: "Demographic Profile",
		socialDetailsTitle: "Social Profile",
		socialDetailsTip: "Social Profile",
		healthAndFitnessDetailsTitle: "Health & fitness Profile",
		healthAndFitnessDetailsTip: "Health & fitness Profile",
		gender: "Gender",
		dateOfBirth: "Date of birth",
		address1: "Address 1",
		address2: "Address 2",
		city: "City",
		state: "State",
		zipCode: "Zip code",
		country: "Country",
		height: "Height",
		weight: "Weight",
		chronicCondition: "Do you have any chronic conditions",
		smoker: "Do you smoke",
		educationLevel: "Highest level of education",
		incomeRange: "Household income range",
		healthCare: "Do you have access to health care",
		pleaseSelectARoleToCreateYourProfile: "Please select a role to create your profile",
		pleaseSelectARoleToCreateYourProfile1: "Please select a role to change your profile",
		profileMessage1:
			" Some information on why we need the demographic profile information and how it can be useful in the fitness determination.",
		organizationName: "Organization Name",
		npiNumber: "NPI number",
		corporateAddress1: "Corporate Address 1",
		corporateAddress2: "Corporate Address 2",
		corporateAffiliation: "Corporate Affiliation",
		corporateAffiliationTip: "Corporate Affiliation Tip",
		corporateAffiliationNote1: "Would you like to track your health and fitness information.",
		roleSelection: "Role Selection",
		basicProfileNote1:
			"Some information on why we need the demographic profile information and how it can be useful in the fitness determination.",
		proceed: "Proceed",
		hospitalAssociated: "Hospital System Associated with",
		enterCardNumber: "Enter Card Number",
		expiryDate: "Expiry Date",
		cvv: "CVV",
		emailId: "Email ID",
		cardDetails: "Card Details",
		cardDetailsTip: "Card Details Tip",
		selectPlan: "Select a plan",
		monthly: "Monthly",
		quarterly: "Quarterly",
		annual: "Annual",
		billedMonthly: "Billed Monthly",
		billedQuarterly: "Billed Quarterly",
		billedAnnually: "Billed Annually",
		month: "month",
		selectDevice: "Select a device",
		addDevice: "Add Device",
		changeEmail: "Change Email",
		yearsOfCoaching: "Years of Coaching",
		male:"Male",
		female:"Female",
	},
	validation: {
		emailFormat: "Invalid Email-Id.",
		required: "This field is required.",
		passwordMatch: "Passwords should match!",
		passwordValidation:
			"Password should contain a combination of uppercase, lowercase, numbers and special characters. The minimum length of the password is 8 characters.",

		passwordValidation1: "Password should contain a combination of uppercase, lowercase, ",
	},
};

